

export const SPRITE_LIBRARY = [
    { url: "https://codejredu.github.io/claudejr/GingerCat.svg", name: "חתול" }, { url: "https://codejredu.github.io/claudejr/Dog.svg", name: "כלב" }, { url: "https://codejredu.github.io/claudejr/Chick.svg", name: "אפרוח" }, { url: "https://codejredu.github.io/claudejr/Rabbit.svg", name: "ארנב" }, { url: "https://codejredu.github.io/claudejr/Beetle.svg", name: "חיפושית" }, { url: "https://codejredu.github.io/claudejr/Monkey.svg", name: "קוף" }, { url: "https://codejredu.github.io/claudejr/Crocodile.svg", name: "תנין" }, { url: "https://codejredu.github.io/claudejr/Rhino.svg", name: "קרנף" }, { url: "https://codejredu.github.io/claudejr/Tiger.svg", name: "טיגריס" }, { url: "https://codejredu.github.io/claudejr/Crab.svg", name: "סרטן" }, { url: "https://codejredu.github.io/claudejr/Flamingo.svg", name: "פלמינגו" }, { url: "https://codejredu.github.io/claudejr/AmericanFootball.svg", name: "פוטבול" }, { url: "https://codejredu.github.io/claudejr/Basketball.svg", name: "כדורסל" }, { url: "https://codejredu.github.io/claudejr/Football.svg", name: "כדורגל" }, { url: "https://codejredu.github.io/claudejr/PistonPlane.svg", name: "מטוס" }, { url: "https://codejredu.github.io/claudejr/ColorfulPlane.svg", name: "מטוס צבעוני" }, { url: "https://codejredu.github.io/claudejr/YellowCar.svg", name: "מכונית" }, { url: "https://codejredu.github.io/claudejr/helicopter-21.svg", name: "מסוק" }, { url: "https://codejredu.github.io/claudejr/SpaceShuttle.svg", name: "מעבורת חלל" }, { url: "https://codejredu.github.io/claudejr/Truck.svg", name: "משאית" }, { url: "https://codejredu.github.io/claudejr/GreenSpottedTree.svg", name: "עץ" }, { url: "https://codejredu.github.io/claudejr/Flower.svg", name: "פרח" }, { url: "https://codejredu.github.io/claudejr/Spindle.svg", name: "כישור" },
    { url: "https://codejredu.github.io/test/assets/ani/waman%20dance.gif", name: "אישה רוקדת" },
    { url: "https://codejredu.github.io/test/assets/ani/CAR.gif", name: "מכונית מרוץ" },
    { url: "https://codejredu.github.io/test/assets/ani/Hedgehog.gif", name: "קיפוד" },
    { url: "https://codejredu.github.io/test/assets/ani/KIDWALK.gif", name: "ילד הולך" },
    { url: "https://codejredu.github.io/test/assets/ani/bee.gif", name: "דבורה" },
    { url: "https://codejredu.github.io/test/assets/ani/bird2.gif", name: "ציפור" },
    { url: "https://codejredu.github.io/test/assets/ani/birdred.gif", name: "ציפור אדומה" },
    { url: "https://codejredu.github.io/test/assets/ani/bycycle.gif", name: "אופניים" },
    { url: "https://codejredu.github.io/test/assets/ani/car1.gif", name: "מכמכונית אדומה" },
    { url: "https://codejredu.github.io/test/assets/ani/dance.gif", name: "רקדן" },
    { url: "https://codejredu.github.io/test/assets/ani/dog.gif", name: "כלב רץ" },
    { url: "https://codejredu.github.io/test/assets/ani/fox.gif", name: "שועל" },
    { url: "https://codejredu.github.io/test/assets/ani/gitarwaman.gif", name: "אישה מנגנת" },
    { url: "https://codejredu.github.io/test/assets/ani/horse.gif", name: "סוס" },
    { url: "https://codejredu.github.io/test/assets/ani/kidwalk1.gif", name: "ילדה הולכת" },
    { url: "https://codejredu.github.io/test/assets/ani/mouse.gif", name: "עכבר" },
    { url: "https://codejredu.github.io/test/assets/ani/ostrich.gif", name: "יען" }
];

const backdropUrlString = `https://codejredu.github.io/test/assets/bg/Amphitheater.svg https://codejredu.github.io/test/assets/bg/canyon.svg https://codejredu.github.io/test/assets/bg/canyon1.svg https://codejredu.github.io/test/assets/bg/castel.svg https://codejredu.github.io/test/assets/bg/castel1.svg https://codejredu.github.io/test/assets/bg/citynight.svg https://codejredu.github.io/test/assets/bg/citynight2.svg https://codejredu.github.io/test/assets/bg/colorfulcity.svg https://codejredu.github.io/test/assets/bg/colorfulcity1.svg https://codejredu.github.io/test/assets/bg/desert.svg https://codejredu.github.io/test/assets/bg/desert1.svg https://codejredu.github.io/test/assets/bg/farm.svg https://codejredu.github.io/test/assets/bg/kidbadroom.svg https://codejredu.github.io/test/assets/bg/kidbadroom1.svg https://codejredu.github.io/test/assets/bg/moon.svg https://codejredu.github.io/test/assets/bg/road1.svg https://codejredu.github.io/test/assets/bg/road2.svg https://codejredu.github.io/test/assets/bg/room1.svg https://codejredu.github.io/test/assets/bg/room2.svg https://codejredu.github.io/test/assets/bg/savanna1.svg https://codejredu.github.io/test/assets/bg/savanna2.svg https://codejredu.github.io/test/assets/bg/school1.svg https://codejredu.github.io/test/assets/bg/slopes1.svg https://codejredu.github.io/test/assets/bg/slopes2.svg https://codejredu.github.io/test/assets/bg/soccer1.svg https://codejredu.github.io/test/assets/bg/soccer2.svg https://codejredu.github.io/test/assets/bg/winter1.svg https://codejredu.github.io/test/assets/bg/winter2.svg https://codejredu.github.io/test/assets/bg/river.svg https://codejredu.github.io/test/assets/bg/cityway.svg https://codejredu.github.io/test/assets/bg/under.svg`;
const BACKDROP_URLS = backdropUrlString.replace(/,/g, ' ').split(/\s+/).filter(url => url.length > 0);
export const BACKDROP_LIBRARY = BACKDROP_URLS.map(url => {
    const name = url.split('/').pop()?.replace('.svg', '') || 'רקע';
    return { url, name };
});

export const SOUND_LIBRARY = [
    { name: "Boat Start", url: "https://codejredu.github.io/test/assets/sound/BoatStart.mp3" }, { name: "Car Door", url: "https://codejredu.github.io/test/assets/sound/CARDOOR.mp3" }, { name: "Elevator Ding", url: "https://codejredu.github.io/test/assets/sound/ElevatorDing.mp3" }, { name: "Water Emptying", url: "https://codejredu.github.io/test/assets/sound/WaterEmptying.mp3" }, { name: "Water Vole Diving", url: "https://codejredu.github.io/test/assets/sound/WaterVole.mp3" }, { name: "Air Land", url: "https://codejredu.github.io/test/assets/sound/airland.mp3" }, { name: "Airplane Cessna", url: "https://codejredu.github.io/test/assets/sound/airplanecessna.mp3" }, { name: "Airplane F15", url: "https://codejredu.github.io/test/assets/sound/airplanef15.mp3" }, { name: "Animal Howl", url: "https://codejredu.github.io/test/assets/sound/animals.mp3" }, { name: "Crowd", url: "https://codejredu.github.io/test/assets/sound/crowds.mp3" }, { name: "Bird Call", url: "https://codejredu.github.io/test/assets/sound/double.mp3" }, { name: "Partridge", url: "https://codejredu.github.io/test/assets/sound/grey.mp3" }, { name: "Pygmy Shrew", url: "https://codejredu.github.io/test/assets/sound/pygmy.mp3" }, { name: "School", url: "https://codejredu.github.io/test/assets/sound/schools.mp3" }, { name: "Flycatcher", url: "https://codejredu.github.io/test/assets/sound/vermilion.mp3" }, { name: "Ding", url: "https://codejredu.github.io/test/assets/sound/dingsoundeffect2.mp3" }, { name: "Dog", url: "https://codejredu.github.io/test/assets/sound/dog.mp3" }, { name: "Leopard", url: "https://codejredu.github.io/test/assets/sound/leopard7.mp3" }, { name: "Link", url: "https://codejredu.github.io/test/assets/sound/link.mp3" }, { name: "Lion Cub", url: "https://codejredu.github.io/test/assets/sound/lioncub.mp3" }, { name: "Whale", url: "https://codejredu.github.io/test/assets/sound/whale3.mp3" },
];